### ISSUE TITLE
Adding username

### ISSUE THREAD

**Issue by cheabdullahjz** [cfloutier/Unity-VNC-Client#11]
Hi,

Current state (Authenticate with the VNC Host using a user supplied password.)

How do I add username as well.

Because the VNC server require username and password to login.

Thanks
Zul

**Comment by cfloutier** [comment]
Hello. Sorry i've not used this client for a while. There were no
authentification for the moment because it was only used for test.

Unfortunately I won't be useful to change how authentication is called

Feel free to propose  a pull request if you find a simple way to correct it

Le mer. 7 juin 2023, 14:01, cheabdullahjz ***@***.***> a
écrit :

**Comment by cheabdullahjz** [comment]
Hi cfloutier,

thanks for your reply.
I guess the easiest way is to change the username to a standard one - e.g.: Admin
Therefore, with this assumed standard username - only password is required for this to work.

Thanks,
Zul
